baseURL = "https://labos-test.herokuapp.com/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "O nama"
url     = "about"
weight  = 2

[[menu.main]]
name    = "Usluge"
url     = "service"
weight  = 3

#[[menu.main]]
#name    = "Gallery"
#url     = "gallery"
#weight  = 4

# [[menu.main]]
# name    = "Blog"
# url     = "blog"
# weight  = 5

[[menu.main]]
name    = "Kontakt"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/labos/vials.jpg"
heading = "Medicinsko-biohemijski laboratorij \"LABOS\""
description = ""
# button
btn     = false
btnText = "Download More"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "LABOS"

[[params.banner.flipText]]
title   = "  "

[[params.banner.flipText]]
title   = "VAMA NA USLUZI "

[[params.banner.flipText]]
title   = " "

# Homepage About Section
[params.about]
enable  = false
title   = "O nama"
content = "O nama text"
image   = "images/labos/vial.jpg"

# Portfolio Section On Homepage
[params.portfolio]
enable  = false
title   = "Do vasih nalaza bez puno cekanja !"
subtitle= "druge informacije o nalazima"

# Pretrage Section On Homepage
[params.pretrage]
enable  = true
title   = "Do vasih nalaza bez puno cekanja !"
subtitle= "druge informacije o nalazima"

# feature Section On Homepage
[params.feature]
enable  = false


# Call to Action
[params.cta]
enable  = true
title   = "VASI UTISCI ?"
content = ""
btnText = "Kontaktirajte nas !"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.posts]
enable  = false
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
